segmented:
    "data/genomes.sequenza.filtered.igv.seg"
gnomad:
    "www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz"
gnomad_index: 
    "www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz.tbi"
gistic_mat:
    "reference/hg38.UCSC.add_miR.160920.refgene.mat"
