reference:
    fasta:
        "www.bcgsc.ca/downloads/morinlab/reference/genome.hg38.fa.gz"
    build:
        "GRCh38"
    vep:
        "www.bcgsc.ca/downloads/morinlab/reference/homo_sapiens_vep_97_GRCh38.tar.gz"
    vep_version:
        "97_GRCh38"
    exac:
        "www.bcgsc.ca/downloads/morinlab/reference/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz"
    exac_tbi:
        "www.bcgsc.ca/downloads/morinlab/reference/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz.tbi"
